### ISSUE TITLE
Retrained model or original

### ISSUE THREAD

**Issue by shilsircar** [wegylexy/rnnoise_wasm#1]
Are you using the same original model or did retrain

**Comment by wegylexy** [comment]
I simply add RNNoise as a submodule in git, and wrap it into an AudioNode in Web Audio API. The original source code of RNNoise is required to compile the WASM.

**Comment by wegylexy** [comment]
You could replace `rnn_data.c` with another model.

If you needed to swap the model dynamically, you would need to implement loading the model in JavaScript as WASM cannot load files.
