### ISSUE TITLE
How can  I use rnnoise in my project ?

### ISSUE THREAD

**Issue by yolin329** [wegylexy/rnnoise_wasm#10]
As the title, how can I use rnnoise in my project? Should I just put 3 files in folder "dist" in my project? But the console shows that RNNoiseNode is not found. I need some help. Thank you very much.

**Comment by wegylexy** [comment]
Please check out the demo folder for sample usage.

**Comment by yolin329** [comment]
Very thanks for your reply. But I didn't find any import / require script in demo code, and I put the files in "dist" in the same folder that I want to use the microphone, but the error shows that RNNoiseNode is not found.  Is that because I put the scripts in wrong place? Thank you.

![image](https://user-images.githubusercontent.com/52409634/142967104-ff646b10-5168-4106-88d6-9d99e731d301.png)

**Comment by wegylexy** [comment]
It is not a module. Just include it the traditional way before the first usage.
https://github.com/wegylexy/rnnoise_wasm/blob/776ca4945d4c0f51212c56d0652c9c3195a48661/demo/index.html#L37

**Comment by yolin329** [comment]
Yes, I include it like below in the script that deal with microphone: 
`require('./rnnoise-runtime.js')` 

But when I want to RNNoiseNode, the error show.
So now, I am stuck.

But anyway I'll keep trying, thank you very much.

**Comment by wegylexy** [comment]
No, it's `<script src="../dist/rnnoise-runtime.js"></script>` in HTML, not `import`/`require`.

Am I not clear enough? It is NOT a module.
