### ISSUE TITLE
Audio glitch on android

### ISSUE THREAD

**Issue by shilsircar** [wegylexy/rnnoise_wasm#2]
On Android looks like the buffer is too small causing audio glitch.

**Comment by wegylexy** [comment]
Which version of Chrome are you using on Android?

**Comment by shilsircar** [comment]
Desktop is fine issue of audio glitch is in Android pixel2 running m84. The issue seems like may be the latency of 128 ms = 2.6 ms @48khz is too small for mobile processing

**Comment by wegylexy** [comment]
According to [the working draft of WebAudio API](https://webaudio.github.io/web-audio-api/#computing-a-block-of-audio), it is always 128. The implementation could include longer intrinsic buffers.

What if you use `ScriptProcessorNode` by hiding the `AudioWorkletNode` detection code?

**Comment by shilsircar** [comment]
Script node works fine. Audio is clear and glitch free.

**Comment by wegylexy** [comment]
May add an option to not use AudioWorklet even available.
