### ISSUE TITLE
The node /demo/server.mjs  command is throwing an error

### ISSUE THREAD

**Issue by EMazzaglia** [wegylexy/rnnoise_wasm#3]
C:\rnnoise_wasm>node demo/server.mjs
internal/modules/cjs/loader.js:975
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\EmilianoMazzaglia\Desktop\rnnoise_wasm\demo\server.mjs
[90m    at Module.load (internal/modules/cjs/loader.js:975:11)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'ERR_REQUIRE_ESM'[39m
}

**Comment by wegylexy** [comment]
@EMazzaglia make sure you are using a current (15) or an active (12, 14) version of node.js

**Comment by EMazzaglia** [comment]
It was that, thank you!
