### ISSUE TITLE
DeepSpeech real-time embedding for rnnoise

### ISSUE THREAD

**Issue by axchanda** [wegylexy/rnnoise_wasm#7]
@wegylexy  Hi, 
I am looking to integrqate the noise reducing feature of rnnnoise with ds. I currently develop application in nodejs & operate at 16-bit 16kHz mono real-time audio.. Can you let me know how to take it forward?

**Comment by wegylexy** [comment]
You'll need to resample your input to float 48kHz for rnnoise yourself as you cannot use WebAudio directly with node.js

**Comment by axchanda** [comment]
@wegylexy I see an implemetation in nodejs wrapper for rnnoise. i need the rnnoise to be working at 16KHz. I can't change my input audio by any means (the architecture & dependencies are fixed). Can you help me in tweaking rnnoise to work at 16KHz?

**Comment by wegylexy** [comment]
You must resample the input to 48kHz from 16kHz as you stated the input must be 16kHz. Resampling is out of scope of this project.
