### ISSUE TITLE
use in broswer

### ISSUE THREAD

**Issue by vishaldhull09** [wegylexy/rnnoise_wasm#8]
https://jmvalin.ca/demo/rnnoise/noise.js

as far as i understood , demo for browser is using this file to load Rnnoise 
any idea how this file is created from the saved model, as I don't want to use node.js

**Comment by wegylexy** [comment]
No, my demo works completely differently from theirs. Mine uses WASM instead of JS for RNNoise.
To use your own model, change https://github.com/xiph/rnnoise/blob/master/src/rnn_data.c in the submodule, and then run https://github.com/wegylexy/rnnoise_wasm/blob/master/build-docker.sh to build a new WASM.

**Comment by vishaldhull09** [comment]
> No, my demo works completely differently from theirs. Mine uses WASM instead of JS for RNNoise.
> To use your own model, change https://github.com/xiph/rnnoise/blob/master/src/rnn_data.c in the submodule, and then run https://github.com/wegylexy/rnnoise_wasm/blob/master/build-docker.sh to build a new WASM.

i was trying to use it directly in browser , I got this
 `Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`
do I have to change anything in code or build file ?

**Comment by wegylexy** [comment]
Your server must specify `Content-Type: application/wasm` in the response header for `*.wasm` files.

**Comment by wegylexy** [comment]
To test on your local machine, you can create a simple `node.js` server.
See https://github.com/wegylexy/rnnoise_wasm/blob/master/demo/server.mjs#L25 .

For `nginx`, config MIME types as follow:
```
    types {
        application/wasm wasm;
    }
```

**Comment by vishaldhull09** [comment]
thanks for the help , i got this
can we save and download input and denoised voice separately....or to upload a voice and get a denoised output

**Comment by wegylexy** [comment]
No downloading/uploading, it all runs in the browser locally. Do whatever you like.
