### ISSUE TITLE
Up- and Down-Scaling from AudioWorklet to rnnoise

### ISSUE THREAD

**Issue by marcce18x1** [wegylexy/rnnoise_wasm#9]
Hi @wegylexy ,
could you explain to me, why you scale the input up and output down before and after the rnnoise_process_frame()?

And thank you for your work.

Edit: I guess it's because AudioWorklet sends 128 Frames 32-bit via the process() function. For rnnoise 16-bit is required. So the scaling is the conversion? Could you explain it in detail for me.

**Comment by wegylexy** [comment]
The models are trained for that range.
